import Head from 'next/head'
import Message from '@/components/Message'
import { useEffect, useState} from 'react'
import Link from 'next/link'
import { db } from '@/utils/firebase'
import { collection, query, orderBy, onSnapshot } from 'firebase/firestore'
import {BiComment} from 'react-icons/bi'

export default function Home() {
  const [allPosts, setAllPosts] = useState([])

  const getPosts = async () =>{
    const collectionRef = collection(db, 'posts')

    //We want the collection order BY the timestamp in descendent
    const queryDate = query(collectionRef, orderBy('timestamp', 'desc'))
    
    //onSnapshot gonna update our data in real time SO if a user make a new POST, it's gonna automatically show it.
    const newPosts = onSnapshot(queryDate, (snapshot) =>{
      setAllPosts(snapshot.docs.map((doc) => ({
        ...doc.data(),
        id : doc.id
      })))
    } )
    return newPosts;
  }

  useEffect(() => {
    getPosts()
  }, [])
  

  return (
    <>
      <Head>
        <title>CreaMinds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='my-12'>
        <h2 className='text-2xl font-medium'>See what other people are posting</h2>
        {allPosts.map((post) => (
          <Message 
            message={post}
            key={post.id}
          >
            <Link href={{ pathname: `/${post.id}`, query: {...post} }}>
              <button className='text-2xl text-brownStrong'>
                <BiComment />
              </button>
            </Link>
          </Message>
        ))}

      </div>
    </>
  )
}
